verbose: true
repository:
    path: github.com/thxcode/kubernetes-event-exporter
build:
    binaries:
        - name: kubernetes-event-exporter
    flags: -a -tags cloud
    ldflags: |
        -X main.Version={{.Version}}
